name: chesapeake_mhw_dask
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - copernicusmarine
  - dask<=2021.10.0
  - geocube
  - geopandas
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - rioxarray
  - scipy
  - seaborn
  - statsmodels
  - xarray
